import { collectionGroup, doc, getDoc, getDocs, limit, query, runTransaction, serverTimestamp, setDoc, where } from "firebase/firestore";
import type { User } from "firebase/auth";
import { db } from "./firebase";
import type { AccountProfile, AppRole } from "./types";
import { collisionPlatformRegistrationId, isPlatformRegistrationId } from "./platformRegistrationId";

const toProfile = (role: AppRole, uid: string, email: string, data: Record<string, unknown>): AccountProfile => ({
  id: uid,
  role,
  name: String(data.name || data.displayName || data.companyName || "IT Connect user"),
  email: String(data.email || email),
  username: data.username ? String(data.username) : undefined,
  imageUrl: data.imageUrl || data.logoURL ? String(data.imageUrl || data.logoURL) : undefined,
  state: data.state ? String(data.state) : undefined,
  platformRegistrationId: data.platformRegistrationId ? String(data.platformRegistrationId) : undefined,
  isActive: data.isActive !== false,
  isApproved: data.isApproved !== false && data.allowed !== false,
  isBlocked: data.isBlocked === true || data.blocked === true,
  isSuspended: data.isSuspended === true || data.suspended === true,
});

export async function resolveProfile(user: User): Promise<AccountProfile> {
  for (const role of ["student", "company"] as const) {
    const snapshot = await getDoc(
      role === "student"
        ? doc(db, "users", "students", "students", user.uid)
        : doc(db, "users", "companies", "companies", user.uid),
    );
    if (snapshot.exists()) return toProfile(role, user.uid, user.email || "", snapshot.data());
  }

  const authorityQuery = query(collectionGroup(db, "authorities"), where("uid", "==", user.uid), limit(1));
  const authority = await getDocs(authorityQuery);
  if (!authority.empty) return toProfile("authority", user.uid, user.email || "", authority.docs[0].data());
  throw new Error("No student, company, or authority profile is linked to this account.");
}

export function assertWorkspaceAccess(profile: AccountProfile): void {
  if (!profile.isActive) throw new Error("This account is inactive.");
  if (!profile.isApproved) throw new Error("This account is awaiting approval.");
  if (profile.isBlocked) throw new Error("This account has been blocked.");
  if (profile.isSuspended) throw new Error("This account is suspended.");
}

export type RegistrationProfile = Record<string, string> & { name: string; phoneNumber: string; imageUrl: string };

export async function createRoleProfile(uid: string, email: string, role: AppRole, profile: RegistrationProfile): Promise<void> {
  const timestamps = { createdAt: serverTimestamp(), updatedAt: serverTimestamp() };
  const consent = { termsAcceptedAt: serverTimestamp(), termsVersion: "2026-08", privacyAcceptedAt: serverTimestamp(), privacyVersion: "2026-08" };
  const reference = role === "student" ? doc(db, "users", "students", "students", uid) : role === "company" ? doc(db, "users", "companies", "companies", uid) : doc(db, "users", "authorities", "authorities", uid);
  if (role === "student") return setDoc(reference, { uid, fullName: profile.name, name: profile.name, email, phoneNumber: profile.phoneNumber, imageUrl: profile.imageUrl, institution: profile.institution, school: profile.institution, courseOfStudy: profile.courseOfStudy, department: profile.department, level: profile.level, matricNumber: profile.matricNumber, registrationNumber: profile.registrationNumber, stateOfOrigin: profile.stateOfOrigin, gender: profile.gender, currentAddress: profile.currentAddress, role: "student", bio: "", username: "", slotBalance: 0, applications: {}, transactionIds: [], isActive: true, isApproved: true, isBlocked: false, isSuspended: false, ...consent, ...timestamps });

  let platformRegistrationId = profile.platformRegistrationId.toUpperCase();
  if (!isPlatformRegistrationId(platformRegistrationId, role)) throw new Error("The IT Connect registration ID format is invalid.");
  const autoGenerated = profile.platformRegistrationIdAuto !== "false";
  const profileData = () => role === "company"
    ? { uid, name: profile.name, companyName: profile.name, email, phoneNumber: profile.phoneNumber, logoURL: profile.imageUrl, platformRegistrationId, industry: profile.industry, state: profile.state, address: profile.address, isUnderAuthority: false, authorityId: profile.underAuthority === "yes" && profile.authoritySelection !== "__missing__" ? profile.authoritySelection : null, authorityName: profile.selectedAuthorityName || profile.requestedAuthorityName || null, requestedAuthorityName: profile.authoritySelection === "__missing__" ? profile.requestedAuthorityName : null, authorityLinkStatus: profile.underAuthority !== "yes" ? "NONE" : profile.authoritySelection === "__missing__" ? "PARTNERSHIP_REQUESTED" : "PENDING", localGovernment: "", description: "", username: "", role: "company", isActive: true, isApproved: false, allowed: false, isVerified: false, isBlocked: false, isSuspended: false, isArchived: false, fcmToken: "", notificationTokens: [], forms: [], potentialtrainee: [], pendingApplications: [], acceptedTrainees: [], currentTrainees: [], completedTrainees: [], rejectedApplications: [], supervisors: [], ...consent, ...timestamps }
    : { id: uid, uid, name: profile.name, authorityName: profile.name, authorityType: profile.authorityType, contactPerson: profile.contactPerson, email, phoneNumber: profile.phoneNumber, logoURL: profile.imageUrl, platformRegistrationId, state: profile.state, address: profile.address, localGovernment: "", description: profile.description, username: "", role: "authority", isActive: true, isApproved: false, allowed: false, isVerified: false, isBlocked: false, isSuspended: false, isArchived: false, fcmToken: "", notificationTokens: [], linkedCompanies: [], pendingApplications: [], approvedApplications: [], rejectedApplications: [], admins: [], supervisors: [], autoApproveAfterAuthority: false, maxCompaniesAllowed: 50, maxApplicationsPerBatch: 100, requirePhysicalLetter: false, totalApplicationsReviewed: 0, currentPendingCount: 0, averageProcessingTimeDays: 0, ...consent, ...timestamps };

  for (let attempt = 0; attempt < 2; attempt += 1) {
    const reservation = doc(db, "platform_registration_ids", platformRegistrationId);
    const reserved = await runTransaction(db, async transaction => { const existing = await transaction.get(reservation); if (existing.exists()) return false; transaction.set(reservation, { uid, role, createdAt: serverTimestamp() }); transaction.set(reference, profileData()); return true; });
    if (reserved) { profile.platformRegistrationId = platformRegistrationId; return; }
    if (!autoGenerated || attempt > 0) throw new Error("That IT Connect registration ID is already reserved. Select Regenerate and try again.");
    platformRegistrationId = collisionPlatformRegistrationId(platformRegistrationId, uid);
  }
}
